create table partei
(
    id         int GENERATED by default on null as IDENTITY
        primary key,
    name       varchar(255)           not null,
    von        date default current_date null,
    bis        date                   null,
    nachfolger int                    null,
    constraint partei_partei_id_fk
        foreign key (nachfolger) references partei (id)
);

create table wahl
(
    id         int GENERATED by default on null as IDENTITY
        primary key,
    wahl_datum date not null
);

create table wahlkreise
(
    nr         varchar2(255) not null
        primary key,
    name       varchar(255)           not null,
    von        date default current_date null,
    bis        date                   null,
    nachfolger varchar2(255)                    null,
    constraint wahlkreise_wahlkreise_nr_fk
        foreign key (nachfolger) references wahlkreise (nr)
);

create table wahl_berechtigte
(
    wahlkreis       varchar2(255)           not null,
    berechtigte     int default 0 not null,
    abgegeben       int           null,
    wahl            int           null,
    wahlbeteiligung int           null,
    constraint wahl_berechtigte_wahl_null_fk
        foreign key (wahl) references wahl (id),
    constraint wahl_berechtigte_wahlkreise_null_fk
        foreign key (wahlkreis) references wahlkreise (nr)
);

create table wahlkreis_stimmen
(
    wahlkreis varchar2(255)           not null,
    stimmen   int default 0 not null,
    prozent   int default 0 null,
    wahl      int           null,
    partei    int           null,
    constraint wahlkreis_stimmen_partei_null_fk
        foreign key (partei) references partei (id),
    constraint wahlkreis_stimmen_wahl_null_fk
        foreign key (wahl) references wahl (id),
    constraint wahlkreis_stimmen_wahlkreise_null_fk
        foreign key (wahlkreis) references wahlkreise (nr)
);


RENAME STAT_DOWNLOAD_NR02_NEW TO STAGEING_STAT_DOWNLOAD_NR02_NEW;
RENAME STAT_DOWNLOAD_NR06_NEW TO STAGEING_STAT_DOWNLOAD_NR06_NEW;
RENAME STAT_DOWNLOAD_NR08_NEW TO STAGEING_STAT_DOWNLOAD_NR08_NEW;
RENAME STAT_DOWNLOAD_NR13_NEW TO STAGEING_STAT_DOWNLOAD_NR13_NEW;
RENAME STAT_DOWNLOAD_NR17_NEW TO STAGEING_STAT_DOWNLOAD_NR17_NEW;
RENAME STAT_DOWNLOAD_NR19_NEW TO STAGEING_STAT_DOWNLOAD_NR19_NEW;