SELECT * FROM (
    SELECT Partei, Wahlkreis, to_char(WAHL_DATUM, 'YYYY') as Wahl, STIMMEN FROM WAHLKREIS_STIMMEN_PIVOT_VIEW
    )
PIVOT (SUM(STIMMEN) FOR Partei IN ('SPÖ', 'ÖVP', 'GRÜNE', 'FPÖ')) WHERE Wahl = '2017';

SELECT * FROM (
    SELECT Partei, Wahlkreis, to_char(WAHL_DATUM) as wd, STIMMEN FROM WAHLKREIS_STIMMEN_PIVOT_VIEW
    )
--PIVOT (SUM(STIMMEN) FOR wd IN ('24.11.02', '29.09.19', '15.10.17'));
PIVOT (SUM(STIMMEN) FOR wd IN ('29.09.19', '15.10.17'))
         WHERE "'15.10.17'" IS NOT NULL and "'29.09.19'" IS NOT NULL AND Partei = 'ÖVP';


SELECT * FROM WAHLKREISE;
SELECT * FROM WAHLKREIS_STIMMEN_PIVOT_VIEW;
SELECT Partei, Wahlkreis, to_char(WAHL_DATUM) as wd, STIMMEN FROM WAHLKREIS_STIMMEN_PIVOT_VIEW ORDER BY wd;

CREATE OR REPLACE VIEW WAHLKREIS_STIMMEN_PIVOT_VIEW AS
    SELECT ww.WAHL_DATUM, w.STIMMEN, wk.NAME as Wahlkreis, (Select p.NAME as a from PARTEI p WHERE w.PARTEI = p.ID) as Partei FROM WAHLKREIS_STIMMEN w
        LEFT JOIN WAHL ww ON w.WAHL = ww.ID
        LEFT JOIN WAHLKREISE wk ON w.WAHLKREIS = wk.ID AND wk.VON <= ww.WAHL_DATUM;