INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum", 'dd.mm.yy') from STAGEING_STAT_DOWNLOAD_NR02_NEW FETCH FIRST 1 ROWS ONLY;
INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum") from STAGEING_STAT_DOWNLOAD_NR06_NEW FETCH FIRST 1 ROWS ONLY;
INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum",'mm-dd-yy') from STAGEING_STAT_DOWNLOAD_NR08_NEW FETCH FIRST 1 ROWS ONLY;
INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum",'mm-dd-yy') from STAGEING_STAT_DOWNLOAD_NR13_NEW FETCH FIRST 1 ROWS ONLY;
INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum") from STAGEING_STAT_DOWNLOAD_NR17_NEW FETCH FIRST 1 ROWS ONLY;
INSERT INTO WAHL(WAHL_DATUM) SELECT to_date("erste Eingabe Datum") from STAGEING_STAT_DOWNLOAD_NR19_NEW FETCH FIRST 1 ROWS ONLY;


INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum", 'dd.mm.yy') FROM STAGEING_STAT_DOWNLOAD_NR02_NEW WHERE "Nr. " is not null;

INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum") FROM STAGEING_STAT_DOWNLOAD_NR06_NEW WHERE "Nr. " is not null;

INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum",'mm-dd-yy') FROM STAGEING_STAT_DOWNLOAD_NR08_NEW WHERE "Nr. " is not null;

INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum",'mm-dd-yy') FROM STAGEING_STAT_DOWNLOAD_NR13_NEW WHERE "Nr. " is not null;

INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum",'mm-dd-yy') FROM STAGEING_STAT_DOWNLOAD_NR17_NEW WHERE "Nr. " is not null;

INSERT ALL INTO WAHLKREISE (NR, NAME, VON)
SELECT "Nr. ", "Name ", to_date("erste Eingabe Datum",'mm-dd-yy') FROM STAGEING_STAT_DOWNLOAD_NR19_NEW WHERE "Nr. " is not null;


INSERT INTO PARTEI (NAME)
SELECT column_name as partei
  FROM all_tab_cols
 WHERE table_name = 'STAGEING_STAT_DOWNLOAD_NR19_NEW' OFFSET 9 ROWS FETCH FIRST 18 ROWS ONLY;